- name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          path: .
          # ПРОВЕРИТЬ ВСЁ: не падать при первой ошибке, а собрать все
          only_warn: true 
          # Проверять скрытые файлы
          check_hidden: true
          # Проверять имена файлов
          check_filenames: true
